name: Main workflow

on: [ push, pull_request ]

jobs:
  # ****************************************
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - name: Check
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install .[test,lint]

      - name: Lint with Ruff
        run: ruff check

      - name: Test with pytest
        run: |
          python -c "import sys; print(sys.version)"
          pytest